In [1]:
import numpy as np
from time import time

with open("input19.txt") as f:
    inp = [x[:-1] for x in f.readlines()]
data = dict()
scan = []
for i in inp:
    if i[:3] == '---':
        data[int(i[12:14])-1] = scan
        scan = []
    elif i != '':
        scan.append(np.array([int(x) for x in i.split(',')]))
data[28] = scan
del data[-1]
data

{0: [array([ 718, -319, -758]),
  array([-765,  759,  419]),
  array([-767, -818,  386]),
  array([ 10, -99,  51]),
  array([-691,  729,  587]),
  array([741, 426, 838]),
  array([-519, -675, -349]),
  array([-689, -870,  398]),
  array([-580, -740, -385]),
  array([ 847,  344, -830]),
  array([ 434, -791,  411]),
  array([ 702, -444, -679]),
  array([-477, -808, -423]),
  array([ 406, -784,  399]),
  array([-263,  636, -688]),
  array([ 584, -366, -691]),
  array([-256,  552, -611]),
  array([-265,  754, -671]),
  array([-758, -751,  491]),
  array([ 37,  78, -47]),
  array([ 609, -768,  472]),
  array([ 906,  400, -817]),
  array([622, 485, 781]),
  array([-734,  844,  514]),
  array([765, 372, 771]),
  array([ 949,  366, -695])],
 1: [array([ 716,  649, -468]),
  array([ 523, -512, -705]),
  array([ 730, -406,  714]),
  array([-425,  466,  641]),
  array([-522, -493, -699]),
  array([-387,  386,  820]),
  array([ 578, -302,  713]),
  array([-587, -554, -735]),
  array([-17, -11,  -7

# Part 1

Scanner 0 is at (0,0,0) and its orientation defines x,y,z axis and positive directions. All other positions will be relative to this one. 
Idea:
Fix a beacon in scanner 0. Then, assume it coincides with a beacon in scanner 1 (for some of the 24 orientations), compute the matrix of positions of scanner 1 relative to scanner 0 (absolute coord) and in the given orientation, and check if there are at least 12 beacons that match. If that is the case, we have identified position and orientation of scanner 1. Otherwise, repeat with next beacon of scanner 1.

In [5]:
def orientations(vector):
    """Returns the positions of the vector for each of the 24 possible orientations"""
    orient = []
    vx, vy, vz = vector[0], vector[1], vector[2]
    return [np.array([vx,vy,vz]), np.array([vy,vz,vx]), np.array([vz,vx,vy]),\
           np.array([-vx,vz,vy]), np.array([vz,vy,-vx]), np.array([vy,-vx,vz]),\
           np.array([vx,-vz,vy]), np.array([-vz,vy,vx]), np.array([vy,vx,-vz]),\
           np.array([vx,vz,-vy]), np.array([vz,-vy,vx]), np.array([-vy,vx,vz]),\
           np.array([-vx,-vy,vz]), np.array([-vy,vz,-vx]), np.array([vz,-vx,-vy]),\
           np.array([vx,-vy,-vz]), np.array([-vy,-vz,vx]), np.array([-vz,vx,-vy]),\
           np.array([-vx,vy,-vz]), np.array([vy,-vz,-vx]), np.array([-vz,-vx,vy]),\
           np.array([-vx,-vz,-vy]), np.array([-vz,-vy,-vx]), np.array([-vy,-vx,-vz])]

def orient_all(scan):
    part = [orientations(x) for x in scan]
    return [[x[i] for x in part] for i in range(24)]
    
def rel_pos(pos1, pos2):
    """Given 2 positions which are the same in diff coord, compute pos of the origin of 2 wrt 1"""
    return pos1 - pos2

def find_pos(scan1, scan2):
    orient_list = orient_all(scan2)
    for i in scan1[:-12]:
        for orient in orient_list:
            for j in orient:
                pos = rel_pos(i,j)
                new_coord = [pos + x for x in orient]
                if sum([all(y==z) for y in scan1 for z in new_coord])>=12:
                    return pos, new_coord
    return False

st=time()
find_pos(data[0], data[1])
end=time()
end-st

2.508531332015991

In [7]:
def solve(data):
    n = len(data)
    pos_list = {0:np.array([0,0,0])}
    coords = {0: data[0]}
    done = []
    while sorted(list(pos_list.keys())) != list(range(n)):
        if [x for x in pos_list.keys() if x not in done]:
            ind1 = [x for x in pos_list.keys() if x not in done][0]
        st = time()
        for ind2 in [x for x in range(n) if x not in pos_list.keys()]:
            print('searching', ind1, ind2)
            res = find_pos(coords[ind1], data[ind2])
            if res:
                print('match!', ind1, ind2)
                pos_list[ind2] = res[0]
                coords[ind2] = res[1]
        end = time()
        print(pos_list.keys())
        print(end-st)
        done.append(ind1)
    return pos_list, coords

st = time()
pos_list, coords = solve(data)
end = time()
end-st

#matches = [(0,6), (0,14), (0,24), (24,2), (24,13), (2,1), (2,22), (13,5), (13,9), (13,18), (1,15), (5,16),\
#          (5,26), (5,28), (9,12), (18,8), (18,11), (15,3), (16,17), (26,7), (26,10), (28,20), (28,23), (28,27),\
#          (8,21), (11,4), (27,19), (19,25)]

searching 0 1
searching 0 2
searching 0 3
searching 0 4
searching 0 5
searching 0 6
match! 0 6
searching 0 7
searching 0 8
searching 0 9
searching 0 10
searching 0 11
searching 0 12
searching 0 13
searching 0 14
match! 0 14
searching 0 15
searching 0 16
searching 0 17
searching 0 18
searching 0 19
searching 0 20
searching 0 21
searching 0 22
searching 0 23
searching 0 24
match! 0 24
searching 0 25
searching 0 26
searching 0 27
searching 0 28
dict_keys([0, 6, 14, 24])
71.7289206981659
searching 6 1
searching 6 2
searching 6 3
searching 6 4
searching 6 5
searching 6 7
searching 6 8
searching 6 9
searching 6 10
searching 6 11
searching 6 12
searching 6 13
searching 6 15
searching 6 16
searching 6 17
searching 6 18
searching 6 19
searching 6 20
searching 6 21
searching 6 22
searching 6 23
searching 6 25
searching 6 26
searching 6 27
searching 6 28
dict_keys([0, 6, 14, 24])
77.29179763793945
searching 14 1
searching 14 2
searching 14 3
searching 14 4
searching 14 5
searching 14 7
searching 

760.4678494930267

In [8]:
pos_list

{0: array([0, 0, 0]),
 6: array([1259,  -25,   96]),
 14: array([ 131, 1177,  119]),
 24: array([   34, -1251,   105]),
 2: array([   24, -1203, -1060]),
 13: array([   42, -1129,  1156]),
 1: array([-1073, -1262, -1084]),
 22: array([  102, -1253, -2391]),
 5: array([    8, -2369,  1232]),
 9: array([-1136, -1251,  1226]),
 18: array([   -8, -1141,  2420]),
 15: array([-1229, -1121, -2263]),
 16: array([  118, -2436,  2536]),
 26: array([-1170, -2479,  1245]),
 28: array([ 1242, -2451,  1335]),
 12: array([-2264, -1282,  1228]),
 8: array([ 1185, -1172,  2461]),
 11: array([   95, -1228,  3607]),
 3: array([-1206, -1134, -3529]),
 17: array([    5, -3612,  2371]),
 7: array([-1222, -2464,    34]),
 10: array([-1103, -3646,  1333]),
 20: array([ 1300, -3697,  1199]),
 23: array([ 1207, -2384,    98]),
 27: array([ 2422, -2319,  1314]),
 21: array([ 1311, -1135,  3694]),
 4: array([-1215, -1176,  3631]),
 19: array([ 2468, -2359,  2369]),
 25: array([ 2376, -2330,  3618])}

In [9]:
beacons = [list(x) for y in coords.values() for x in y]
unique_beacons = [list(x) for x in set(tuple(x) for x in beacons)]
len(unique_beacons)

367

# Part 2

In [10]:
def manhattan(p1,p2):
    return abs(p1[0]-p2[0]) + abs(p1[1]-p2[1]) + abs(p1[2]-p2[2])

def max_dist(pos_list):
    res = 0
    for i in pos_list.values():
        for j in pos_list.values():
            part = manhattan(i,j)
            if part > res:
                res = part
    return res

max_dist(pos_list)

11925